admin:
  build: spring-boot-docker-run
  volumes:
    - ./spring-boot-admin:/data
    - ~/.m2:/root/.m2
  ports:
    - 8080:8080
web1:
  build: spring-boot-docker-run
  volumes: 
    - ./spring-boot-webapp-1:/data
    - ~/.m2:/root/.m2
  ports:
    - 8081:8080
  links:
    - admin
  command: mvn spring-boot:run -Dspring.boot.admin.client.url=http://localhost:8081
web2:
  build: spring-boot-docker-run
  volumes: 
    - ./spring-boot-webapp-2:/data
    - ~/.m2:/root/.m2
  ports:
    - 8082:8080
  links:
    - admin
  command: mvn spring-boot:run -Dspring.boot.admin.client.url=http://localhost:8082
